name: 'Free disk space'
description: 'Remove unnecessary pre-installed tools to free up disk space on GitHub Actions runners'
runs:
  using: 'composite'
  steps:
    - run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc \
          /opt/hostedtoolcache/CodeQL /usr/local/share/boost /usr/share/swift \
          /opt/hostedtoolcache/go /opt/hostedtoolcache/node /opt/hostedtoolcache/Ruby \
          /opt/hostedtoolcache/PyPy /opt/hostedtoolcache/Python /opt/microsoft \
          /usr/share/az_* /usr/share/gradle-* /usr/share/miniconda /usr/share/kotlinc \
          /usr/local/graalvm /usr/local/lib/heroku /usr/local/share/chromium \
          /usr/local/share/powershell /usr/local/share/edge_driver \
          /usr/local/share/gecko_driver /usr/local/share/chromedriver-* \
          /usr/local/share/chrome /usr/local/share/phantomjs*
        docker system prune -af || true
        df -h
      shell: bash
