name: Purge cloudflare cache
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      CLOUDFLARE_ZONE:
        description: "Cloudflare Zone ID"
        required: true
      CLOUDFLARE_TOKEN:
        description: "Cloudflare API Token"
        required: true
  repository_dispatch:
    types: [ update-content ]

jobs:
  purge-cache:
    runs-on: ubuntu-24.04
    steps:
      - name: Purge cache all
        uses: jakejarvis/cloudflare-purge-action@master
        if: ${{ github.event_name != 'repository_dispatch' }}
        env:
          # Zone is required by both authentication methods
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

      - name: Purge cache all
        uses: jakejarvis/cloudflare-purge-action@master
        if: ${{ github.event_name == 'repository_dispatch' }}
        env:
          # Zone is required by both authentication methods
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          PURGE_URLS: '["https://blog.romira.dev/", "https://blog.romira.dev/articles/${{ github.event.client_payload.id }}"]'
