name: Purge cloudflare cache
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      CLOUDFLARE_ZONE:
        description: "Cloudflare Zone ID"
        required: true
      CLOUDFLARE_TOKEN:
        description: "Cloudflare API Token"
        required: true

jobs:
  purge-cache:
    runs-on: ubuntu-24.04
    steps:
      - name: Purge cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          # Zone is required by both authentication methods
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
