name: Purge cloudflare cache
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      CLOUDFLARE_ZONE:
        description: "Cloudflare Zone ID"
        required: true
      CLOUDFLARE_TOKEN:
        description: "Cloudflare API Token"
        required: true
  repository_dispatch:
    types: [ update-content ]

jobs:
  purge-cache:
    runs-on: ubuntu-24.04
    env:
      ORIGIN_URL: https://blog.romira.dev
    steps:
      - name: Purge cache all
        uses: jakejarvis/cloudflare-purge-action@master
        if: ${{ github.event_name != 'repository_dispatch' }}
        env:
          # Zone is required by both authentication methods
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

      - name: Purge cache specific
        uses: jakejarvis/cloudflare-purge-action@master
        if: ${{ github.event_name == 'repository_dispatch' }}
        env:
          # Zone is required by both authentication methods
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          PURGE_URLS: '["${{ env.ORIGIN_URL }}", 
                        "${{ env.ORIGIN_URL }}/api/get_articles_handler", 
                        "${{ env.ORIGIN_URL }}/api/get_author_handler", 
                        "${{ env.ORIGIN_URL }}/api/get_article_handler?id=${{ github.event.client_payload.id }}&", 
                        "${{ env.ORIGIN_URL }}/articles/${{ github.event.client_payload.id }}"]'
